### ISSUE TITLE
Importing a file and adding constrains can turn problems wrongly unsatisfiable

### ISSUE THREAD

**Issue by rubenkindt** [CPMpy/cpmpy#158]
solver: not relevant
CPMpy: version v0.9.9 commit e79b3afedc934a9437c2ddb3a9f54d7e2d7bd3ee

When importing a file and adding new constraints with variables containing the same variable name (both generated or user-defined names) will cause the solver to treat the variable as one and the same, which can cause wrong solutions.

generating a file to import:
```python 
from cpmpy import *

i = intvar(lb=3, ub=6) # auto name IV0
m = Model()
m += i == 4
m.to_file("1")
```

```python 
from cpmpy import *

m2 = Model().from_file("1")
j = intvar(lb=0, ub=10) # auto name again IV0
m2 += j == 5
m2.solve()
print(m2.status())
```

expected behavior: 
Threat both variable as two separate variables and solve the problem.

bug found while working on my master thesis.

**Comment by tias** [comment]
Interesting.

1. a variable's name is its unique identifier. If you give two variables the same name, you run into trouble. Even if we would support it at CPMpy side, things would quickly go wrong for different solvers...

I should document this more explicitly, e.g. in https://cpmpy.readthedocs.io/en/latest/modeling.html too.

2. the case you provide is actually not misuse... the user can not know they are reusing a variable name, because they are not actually naming anything. I think the proper fix here is to increase the magic variable counter when doing `from_file()`, based on the highest appearing IV* and BV* names in the 'fromfile' model... TODO ; )
