### ISSUE TITLE
malloc(): Not enough space in some MiniZinc subsolvers

### ISSUE THREAD

**Issue by rubenkindt** [CPMpy/cpmpy#164]
solver: MiniZinc's int, cp, lcg and chuffed subsolvers
CPMpy: version v0.9.9 commit e79b3afedc934a9437c2ddb3a9f54d7e2d7bd3ee
minizinc-python release version 0.7.0 commit {https://github.com/MiniZinc/minizinc-python/commit/a195cf63fcfbc98665d70ab64efb5424db25bd7e)

While using CPMpy to model a problem and some Minzinc's subsolvers to solve the problem, I found a malloc() error. This error is probably for https://github.com/MiniZinc/minizinc-python, but after advise from Ignace I'm posting it here just to be sure. The amount of constraints are minimized, but the remaining constraints can probably still smaller.

[almostMinimimal.zip](https://github.com/CPMpy/cpmpy/files/10056699/almostMinimimal.zip)
```python
from cpmpy import *

file = "almostMinimimal" # don't forget to unzip first
m = Model().from_file(file)
m.solve(solver="minizinc:lcg") # or int, cp, lcg, chuffed
```

bug found while working on my master thesis.

**Comment by tias** [comment]
Hi Ruben,

Yes, so either our translation to MiniZinc is too naive (for example, because we do not identify sufficiently tight domains), or it is a bug in python-minizinc or actually the solver itself.

We should look at the raw minizinc text to be able to judge that. If it is on the solver or mzn side, we should file it upstream.

There is no really good way to get the minizinc textfile from a CPM_MiniZinc model I found, so I hacked it like this:

```
import requests
import tempfile
import os
from io import BytesIO
from zipfile import ZipFile

from cpmpy import *

url = "https://github.com/CPMpy/cpmpy/files/10056699/almostMinimimal.zip"

headers = {"User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36'}
response = requests.get(url, headers=headers)
myzip = ZipFile(BytesIO(response.content))
# make temp dir
tmpdir = tempfile.mkdtemp() 
myzip.extractall(tmpdir)
zipfnames = myzip.namelist()

cpm_file = os.path.join(tmpdir, zipfnames[0])
m = Model().from_file(cpm_file)
s = SolverLookup.get("minizinc", m)
print("".join(map(str, s.mzn_model._code_fragments)))
```

(generally applicable if you change the url)

which returns:

```
% Generated by CPMpy
include "globals.mzn";

var bool: BV486914;
var -2147483659..2147483636: IV10;
var 0..2147483659: IV11;
var 0..5: x_1;
var -2147483648..2147483647: IV3;
constraint xorall([false,true,true,((BV486914) \/ ((abs(IV10)) == (IV11))) /\ ((BV486914) \/ ((
    let { array[int] of var int: arr=array1d(0..5,[1,2,5,7,13,21]) } in
      arr[x_1]) == (IV3)))]);
```

So... the minizinc people will probably not accept this as a bug. If you create a nearly-unbounded variable, and a solver will bitblast the domain, then yeah, you run out of memory.

So the real question is: why does IV3 not have a more proper domain? e.g 1..21

That is the CPMpy bug here...

**Comment by tias** [comment]
(note that it ties to #96, which is one of the multiple open points that your fuzzer so accurately identifies ; )

**Comment by rubenkindt** [comment]
Thanks! This explanation helped me with a (what I now know to be the same) bug I struggled to reproduce.

**Comment by tias** [comment]
I imagine it might have been hidden to you because we do not show the domains of the variables in our prints...

The debugpage has a small part that shows you how to look at both the (flat) constriants and the variables, this can reveal bugs due to too-wide domains:

```python
from cpmpy.transformations.flatten_model import flatten_constraint, flatten_model
from cpmpy.transformations.get_variables import print_variables
mf = flatten_model(model)
print_variables(mf)
print(mf)
```

BTW. For the above bug, the model seems to already contain full-integer-ranged variables? Where did you get these from? Did CPMpy generate them? Because it is considered extremely bad practice to use such extremely large domains...

**Comment by rubenkindt** [comment]
The file above got created by taking a random (sub)solver and a random existing (solvable) problem executing 4 of the 40 created sat-preserving transformations on some (or all) the constraints,then test if the problem is still solve-able and extracting it if it failed via ```to_file```. 
I did find some places where I take a random argument's ".lb" without first checking if that argument had a ".lb". So it could be that I set those values to gibberish assuming Python allowed it (normally Python would crash I think). Tomorrow I will search further to see if this is what happened.

**Comment by tias** [comment]
No, OK, then it is on our side, e.g.

```python
x1 = intvar(0,5, name="x1")
c = cpm_array([1,2,5,7,13,21])[x1]
cc = flatten_constraint(abs(c) > 5)
print_variables(cc)
```
should have IV1: 1..21
but it is -int..int and that is what you carry along in your mutations. That is the bug we should fix
