### ISSUE TITLE
MiniZinc error: Memory violation detected (segmentation fault).

### ISSUE THREAD

**Issue by rubenkindt** [CPMpy/cpmpy#165]
solver: MiniZinc's int, cp, lcg and chuffed subsolvers
CPMpy: version v0.9.9 commit e79b3afedc934a9437c2ddb3a9f54d7e2d7bd3ee
minizinc-python release version 0.7.0 commit {https://github.com/MiniZinc/minizinc-python/commit/a195cf63fcfbc98665d70ab64efb5424db25bd7e)

While using CPMpy to model a problem and some Minzinc's subsolvers to solve the problem, I found a memory violation. This error is probably for https://github.com/MiniZinc/minizinc-python, but after advise I'm posting it here just to be sure. Due to the error minimizing the bug was harder and therefore the inputs may not be minimal. Could be related to the malloc crash of #164.

[memory violation seg fault minizinc.zip](https://github.com/CPMpy/cpmpy/files/10056742/memory.violation.seg.fault.minizinc.zip)

```python
from cpmpy import *

file = "inputFile" # don't forget to unzip first
m = Model().from_file(file)
m.solve(solver="minizinc:chuffed")
```

Bug found while working on my master thesis.

**Comment by Dimosts** [comment]
After correcting the issue with the variable names, the model of the file does not run any more, due to "Minizinc only accept names with alphabetic characters, digits and underscores. First character must be an alphabetic character".

Printing the variables to see what's going on, I see this:

```
    x[6,2,0]: 0..8
    BV78076: 0..1
    600: 0..1
    BV78524: 0..1
    ...
```

There are many variables that have integer names ... Thus cannot reproduce this anymore. Anyway, this is connected to pull request #224
