### ISSUE TITLE
Comparing a boolean expression with an intvar crashes most solvers

### ISSUE THREAD

**Issue by Wout4** [CPMpy/cpmpy#190]
using '==' between a boolean subexpression and an intvar crashes the following solvers: gurobi, pysat and ortools

example:
iv = intvar(0,9, shape=2)
m1 = Model((iv[1] == 2) == iv[0])
s = SolverLookup.get("pysat", m1) # also crashes gurobi and ortools
s.solve()

Other comparision operators (<,>,<=,>=) only crash pysat
example:
m1 = Model((iv[1] == 2) >= iv[0])

expected behavior: we seem to treat the number 1 as True and all other ints as False, so I guess we should keep this consistent like that?

**Comment by Wout4** [comment]
Correction:
1 is True and 0 is False, using other ints as a boolean value gives an inconsistent model:
m1 = Model([(iv[1] == 2) == iv[0], iv[0] == 2]) # has no solutions

**Comment by JoD** [comment]
These comparisons should work, right? We should allow (explicit or implicit) conversion from bool to int (the other way around is different of course).

We can use explicit conversion (require the use of a builtin constraint "to_int(bool)") or implicit (don't require anything). But in the end, True -> 1 and False -> 0, and from that the rest should work. E.g., `(iv[1] == 2) == iv[0]` means that iv[0] is 1 if iv[1]==2, and otherwise iv[0] is 0. Whether or not the subsolver has solutions should follow from interaction with other constraints.

**Comment by Wout4** [comment]
I will go for the implicit conversion, which seems to make intuitive sense to me.
