### ISSUE TITLE
Python floor division operator (//)

### ISSUE THREAD

**Issue by jsuchenia** [CPMpy/cpmpy#199]
During my work with cpmpy library I have to use two different operators for a division
* Single slash for `intvar()` objects
* Double slash (aka floor division) for Python3 `int()` - as normal division generates `float` value instead of `int`

It will be convenient if `cpmpy` implements both in the same way for simplicity - then we can have the same code for `int()` and `intvar()`

**Comment by tias** [comment]
Actually since we only support integer variables, we conceptually only support floordivision...

Adding floordivision is trivial and we should do it asap. But this raises the question,

  1. should we continue to support classic `/`?
  2. should we change the way we print division to be `//`?

I think the floordivision in Python is less well known, and even unknown to people coming from different modeling languages. So perhaps we should 1. keep `/` but maybe throw a deprecationwarning that on integer varaibles `\\` should be used, and 2. indeed change our printing of div to `//`?

@IgnaceBleukx @JoD @Wout4 opinions?

**Comment by Wout4** [comment]
It makes a lot of sense to have the same notation for int() as for intvar(), and since we only support floor division on intvar we should probably use '//' here. keeping / with a warning seems ok to me.
And if someone want's to have a float constant like 7 / 3 that still stays possible, although I'm not sure there is a use case for that.

**Comment by IgnaceBleukx** [comment]
1. I think we can keep both, a deprication warning might be good. We did the same for the camel-cased `IntVar` and non-camel-cased `alldifferent` I think. This raises the question: do we actually stop supporting `/` when we do a stable release?
2. We should definitely change the printing to `//`
