### ISSUE TITLE
Error Weights Objective

### ISSUE THREAD

**Issue by ElFosco** [CPMpy/cpmpy#243]
### 
``` python3
from cpmpy import *

model = Model()
test = intvar(0, 1000, name="test")
model.maximize(10*(test*0.5))
model.solve()

print(test.value())
```

In this case the error returned is 

```
IntVar lowerbound must be integer <class 'float'> 0.0
```

However if I change slightly the code 
``` python3
from cpmpy import *

model = Model()
test = intvar(0, 1000, name="test")
model.maximize(10*(test//2))
model.solve()

print(test.value())
```
The code works.

**Comment by Dimosts** [comment]
During the bounds calculation in flatten_model.py, for weighted sums we have the following:

```
            lb, ub = bounds.min(axis=0).sum(), bounds.max(axis=0).sum() # for every column is axis=0...
            ivar = _IntVarImpl(lb, ub)
```

When the sum is calculated with this, it ends up being a real number instead of an int, when the weight is float. Thus, when in the next line a new intvar is created, the problem occurs due to the lower bound (and the same for upper bound) not being an integer.. 

This could be solved if when calculating the bounds for wsum, we take these weights into account and then convert the bounds to an int before the initialization of the new IntVar. Also, after that we should check if this creates any other problem.

I can be assigned the issue and check it, in case noone else is working in the same things. Is anyone working on this?

**Comment by Dimosts** [comment]
Ok it is related to Pull request #224, @Wout4 is working on it

**Comment by Wout4** [comment]
Model([iv[1] * 0.5>2]).solve() crashes with an ortools error
