### ISSUE TITLE
precondition of linearize_constraint not clear

### ISSUE THREAD

**Issue by Wout4** [CPMpy/cpmpy#267]
Bug in linearize_constraint, found while fuzztesting with only_positive_bv_morph (since this excpects linear input but did not get it)

bv = boolvar(3)
cons = [(bv[0] & bv[1]).implies(bv[2] == 0)]
print(linearize_constraint(cons))

**Comment by IgnaceBleukx** [comment]
This constraint is not flat (which is a precondition for `linearize` so it actually works as expected : )

**Comment by IgnaceBleukx** [comment]
That one is fine actually. 
For a constraint to be flat, the implication has to look like: `bv -> BoolExpr` or `BoolExpr -> bv`.
So actually the problem here is that linearize only supports the subset `bv -> BoolExpr` (which can be achieved by calling `only_bv_implies`). This should be stated clearly in the documentation of `linearize`
