### ISSUE TITLE
min() not solving for minimum

### ISSUE THREAD

**Issue by toddstrader** [CPMpy/cpmpy#321]
The docs say that `min()` is supported in the constraints:
https://cpmpy.readthedocs.io/en/latest/modeling.html

However, my model does not appear to be solving for the minimum:
```
In [43]: a = cpmpy.intvar(0, 2)

In [44]: b = cpmpy.intvar(0, 2)

In [45]: mod = cpmpy.model.Model(a + b < 3, min(a, b) == mab)

In [46]: mod.solveAll(display=lambda: print(f"{a.value()=} {b.value()=} {mab.value()=}"))
a.value()=0 b.value()=0 mab.value()=0
a.value()=0 b.value()=1 mab.value()=1
a.value()=0 b.value()=2 mab.value()=2
a.value()=1 b.value()=0 mab.value()=0
a.value()=2 b.value()=0 mab.value()=0
a.value()=1 b.value()=1 mab.value()=1
Out[46]: 6
```

E.g., for the second solution `mab` should be 0.  Can you tell me what I'm doing wrong here?

**Comment by Dimosts** [comment]
Hello,

the issue is that the provided code uses the python built in min() function instead of the cpmpy.min() one. This means that the min() function is not actually returning the min() constraint, but the minimum "value", and as both have the same (None), it just directly returns the second (last) variable.

If I print the model using the built in min() function, we get the following:

```
Constraints:
    (IV0) + (IV1) < 3
    (IV1) == (IV2)
Objective: None
```

In order to create the desired constraint, the cpmpy.min() function should be used, i.e. 
`mod = cpmpy.model.Model(a + b < 3, cpmpy.min([a, b]) == mab)`

which returns the following solutions:

a.value()=0 b.value()=0 mab.value()=0
a.value()=0 b.value()=1 mab.value()=0
a.value()=0 b.value()=2 mab.value()=0
a.value()=1 b.value()=0 mab.value()=0
a.value()=2 b.value()=0 mab.value()=0
a.value()=1 b.value()=1 mab.value()=1

**Comment by toddstrader** [comment]
Fantastic, thanks for the help.  Also, I didn't know you could stringify the model.  That's super handy.
