### ISSUE TITLE
boolval.implies leads to error

### ISSUE THREAD

**Issue by Wout4** [CPMpy/cpmpy#368]
Model(BoolVal(False).implies(bv)).solve()) gives an error in ortools.
Not sure how to fix

**Comment by IgnaceBleukx** [comment]
Probably this gets simplified to `True` by `simplify_boolean`...
The error comes up after the solve, when we try to fetch the value for all variables in the model.
We could call `solver_vars` on the variables in the constraints **before** transformations are applied.
But then what to set the value of the variables that gets simplified away? Just a random value from its domain? I would be fine with that actually.

**Comment by Wout4** [comment]
random value makes sense, that's what happens when multiple solutions exist anyway. Would that work for solve_all as well?

**Comment by Dimosts** [comment]
I would say better take the values of the domain in a lexico order, min first. even if we give it to OR-Tools with a fake constraint, e.g. IV < 10000 in an iv with ub = 100, OR-Tools will do exactly that and the solutions will be in a min first order. So we should do the same, instead of random value, which will also help us in the solve_all case

**Comment by tias** [comment]
it doesnt have a value, so the value should be (remain) None.
we should catch that we might check on a variable that is unknown to ortools, will add that

**Comment by tias** [comment]
the `solveAll()` will indeed return 1 with the proposed 'fix'. Doing that properly means we should have an option that keeps all variables alive or so... not super obvious and out of scope of this bug
