### ISSUE TITLE
No solution with 0 in domain

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#41]
The following model (archery puzzle) give no solution at all when the `d` variable has`0..100` as domain:
```
from cpmpy import *
import numpy as np
from cpmpy.solvers import *

def archery_puzzle():
  
  targets = [16, 17, 23, 24, 39, 40]
  n = len(targets)

  target = 100

  # variables
  x = intvar(0,100,shape=n,name="x")
  z = intvar(0,100,name="z")
  d = intvar(0,100,name="d")

  # constraints
  model = Model([z == sum(x*targets),
                            d == abs(target-z)
                            ],
                            minimize=d
                            )

  ss = CPM_ortools(model)
  num_solutions = 0
  if ss.solve():
    num_solutions += 1
    print("z:", z.value())
    print("d:", d.value())
    xx = x.value()
    print("x:",xx)
    print("\n".join(["%i hits on score %i" % (xx[i], targets[i]) for i in range(n) if xx[i] > 0]))
    print()

  print("num_solutions:", num_solutions)

archery_puzzle()
```

After changing the domains for `d` to `1..100` then there is a solution:
```
z: 99
d: 1
x: [3 3 0 0 0 0]
3 hits on score 16
3 hits on score 17
```

However, the optimal solution has `d=0`:
```
z: 100
d: 0
2 hits on score 16
4 hits on score 17
```

Interestingly, without the `minimize=d` statement, the following solution is printed, i.e. the optimal solutions:
```
z: 100
d: 0
x: [2 4 0 0 0 0]
2 hits on score 16
4 hits on score 17
```

So it seems that `minimize` is the culprit.

**Comment by tias** [comment]
Hi Hakan,

The culprit is `if ss.solve():`...

Since you are solving a minimization problem, it will return the value of the optimal solution. That value is '0.0'.

and python interprets 'if 0' as 'False', so the rest of your code is not run...


You should either remove the `if ss.solve()` for optimisaiton problems or change it to `if ss.solve() is not False:`


I want the solver to be usable as oracle, hence answering the answer (True/False or integer value). But I realize this 'answering Bool or int' could be surprising... I also notice I only use it as an oracle in the satisfiable case... I'm not sure I should change this.
In the examples, I consistently don't check 'if ss.solve()' for optimisation problems...

**Comment by hakank** [comment]
Thanks for the answer. Tias.

I tend use use the `if ....` construct even for optimization problems since then it's easier to change to a `while`  to make it a sat problem, e.g for printing all (optimal) solutions.
