### ISSUE TITLE
Possibility of modeling Generalized Disjunctive Programs

### ISSUE THREAD

**Issue by bernalde** [CPMpy/cpmpy#429]
Hi,
Great package.
I have struggled to realize the capabilities of modeling Generalized Disjunctive Programs using CPMPY. The problem type is succinctly described here 
```math
 min f(x); \\
\textrm{s.t.}  g(x) \leq 0; \\
\bigvee_{i \in D_k} \begin{bmatrix}
  Y_{ik}  \\
  r_{ik}(x) \leq 0
\end{bmatrix}, \, k \in K;
\\
\Omega (Y) = \textrm{True};
L \leq x \leq U, \, x  \in \mathbb R^n;
Y_{ik}   \in  \{\textrm{True, False} \}
```
https://www.gams.com/latest/docs/UG_EMP_DisjunctiveProgramming.html#UG_EMP_DisjunctiveProgramming_GPD

Would it be possible? I noticed some mappings from indicator variables to MIP using Big-M constraints.

**Comment by Wout4** [comment]
There seems to be some formatting issue in your post, but from the link it looks like you need continuous variables?
The only solver within CPMpy that supports this is Gurobi (for which you would need a license). And you would have to directly access the gurobi solver object to create these variables since it is not (yet) supported within CPMpy. This is explained at the bottom of our documentation page: https://cpmpy.readthedocs.io/en/latest/modeling.html

**Comment by bernalde** [comment]
My bad, I corrected the math. Indeed, the question is whether there are modeling capabilities in this package to write this kind of model (integrating logical propositions and algebraic constraints seems doable, but I wonder about the disjunctions).

**Comment by Wout4** [comment]
I don't totally grasp the problem, but the disjunctions should be doable.
You can define a 2 dimensional variable array Y and then you can simply write a loop constructing the constraints `k[i] == (Y[i,k].implies(r(i,k,x) < 0))`

to connect them all in a disjunction you can just use cpmpy's any() : `any(k)`

Of course the feasibility depends then on what r exactly is, since you have to implement r as well..
