### ISSUE TITLE
Problem with xor constraint

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#44]
The following constraint using `^` (xor)
```python
M6 == (M4 ^ M5)
```
throws an error:
```
"can not reify a reification"
```

The following works, however:
```python
M6 == (M4 + M5 == 1)
```

(This is from my monks and doors model: http://hakank.org/cmpy/monks_and_doors.py .)

**Comment by tias** [comment]
Hi Hakan,

Seems to be a combination of two bugs,
- CPMpy did not support negated_normal for xor yet (fixed in f90a86182500c9210ed3202a435090112601c813)
- ORtools does not support reification of a Xor constraint, see https://github.com/google/or-tools/issues/800
  they recommend switching to a sum (like you did above) instead, so now we do this in CPMpy behind the scenes too (fixed in 906d244acbf37efe29a296fdc244aa15a71508b8)

It will be a few days before a new beta with these fixes is released.
