### ISSUE TITLE
Broadcasting * and + differs

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#46]
The following model tests some different cases of broadcasting, for example `*` and `+`. The way they works (are interpreted) are different:
* `y == x*2` is done element wise
* `y == x+1` is interpreted as `sum(x)+1`

I would have expected that `+` would work the same as `*` in this context.

```
import numpy as np
from cpmpy import *
from cpmpy.solvers import *

def get_different_solution(m,x):
  m += [any([t.value() != t for t in x])]

def print_model_and_variables(model):
  from cpmpy.transformations.flatten_model import flatten_constraint, flatten_model
  from cpmpy.transformations.get_variables import print_variables
  print("Model:")
  print(model)
  print("\nFlattened model and variables:")
  mf = flatten_model(model)
  print_variables(mf)
  print(mf)
  print()


def numpy_test(n):

  # variables
  x = intvar(0,n*n,shape=(n,),name="x")
  y = intvar(0,n**4,shape=(n,),name="y")

  # constraints
  model = Model([AllDifferent(x),
                 # AllDifferent(y),
                 y == 2*x # This works as expected
                 # y == x+1 # This does not: y = sum(x) + 1
                 # x == y-1 # No solution!
                 # y == x*x # OK
                 # y == x % 2 # OK
                 # x % 2 == 0, # No solution (modulo with 0 domain?)
                 # y == x / 2, # OK
                 # y == (x / 2)+1, # OK?
                 ])

  print_model_and_variables(model)
  
  ss = CPM_ortools(model)
  num_solutions = 0
  while ss.solve() is not False:
    num_solutions += 1
    print("x:")
    print(x.value())
    print("y:")
    print(y.value())
    print(flush=True)
    get_different_solution(ss,list(x.flat)+list(y.flat))
  
n = 3
numpy_test(n)
```

The model for `y = x*2`:
```
Constraints:
    alldifferent(x[0],x[1],x[2])
    [(y[0]) == (2 * (x[0])) (y[1]) == (2 * (x[1])) (y[2]) == (2 * (x[2]))]
```

The model for `y == x+1`:
```
Constraints:
    alldifferent(x[0],x[1],x[2])
    [(y[0]) == (sum([x[0], x[1], x[2], 1]))
 (y[1]) == (sum([x[0], x[1], x[2], 1]))
 (y[2]) == (sum([x[0], x[1], x[2], 1]))]
```

If this is not fixable: Is there a broadcast version to do an element-wise version of `y == x+1`? 
A non-broadcast version works, of course: ` [y[i] == x[i]+1 for i in range(n)]`.

**Comment by tias** [comment]
Quick answer:
`y == np.add(x,1)`

I will look into what standard numpy behaviour is for */+ on arrays, we follow that.

**Comment by tias** [comment]
OK, it looks like I had forgotten to add some vectorized operations, including sum.

Thanks for noticing!

Thanks to this change, it is now also possible to write, e.g. for scheduling problems, the intuitive:

```
# enforce end = start + duration
model += (end == start + dur)
```
for any (common) dimension of end/start/dur.

instead of model += (end == np.sum(start + dur)) or blasting out the lists...


There is one caveat that we used in one of our own examples...
let `v = intvar(1,6, shape=(2,3))` or any other n-dimensional array with n>1; then you **should not** do sum(v) but `np.sum(v)` if you want to take the sum over __all__ elements. The latter does this, but the former does v[0] + v[1] + v[2], which leads to vectorized operations on the second dimensions...

**Comment by hakank** [comment]
Great. 

Yes, I realize that fixing this will break some of the existing code. 

In the summary of a matrix, wouldn't `x.sum()` be the same as `np.sum(x)`? I would personally prefer `x.sum()` over `np.sum(x)` (if that works).

**Comment by tias** [comment]
yes! `x.sum()` works equally well and is indeed tidier because no need to include the np library explicitly.

Actually, now that you mention it, in case of long arrays/expressions, x.sum() is probably preferred over sum(x) because the latter decomposes it into `((x[0] + x[1]) + x[2]) + ...` while the former immediately builds an Operator("sum", x) expression.
