### ISSUE TITLE
int64 not json serializable

### ISSUE THREAD

**Issue by tias** [CPMpy/cpmpy#484]
Some faciliyt location model, a CPMpy expression, when calling `exp.value()` on it, it returned an int64 (which was not serializable)

Why do we create non-standard types? Actually we don't, but numpy does somewhere, and we go along with it...

@kostis-init can provide the model

**Comment by kostis-init** [comment]
This is the model in which `total_cost.value()` returns an int64:

```
import cpmpy as cp
import numpy as np
import json

# Data
warehouse_s = ["New York", "Los Angeles", "Chicago", "Atlanta"]
fixed_costs = [400, 500, 300, 150]
max_shipping = 100
demands = [80, 70, 40]
shipping_costs = [
    [20, 40, 50],  # New York to regions 1, 2, 3
    [48, 15, 26],  # Los Angeles to regions 1, 2, 3
    [26, 35, 18],  # Chicago to regions 1, 2, 3
    [24, 50, 35]   # Atlanta to regions 1, 2, 3
]

num_warehouses = len(warehouse_s)
num_regions = len(demands)

# Decision variables
open_warehouse = cp.boolvar(shape=num_warehouses, name="open_warehouse")
ships = cp.intvar(0, max_shipping, shape=(num_warehouses, num_regions), name="ships")

# Constraints
constraints = []

# 1. If the New York warehouse is opened, then the Los Angeles warehouse must also be opened.
constraints.append(open_warehouse[0].implies(open_warehouse[1]))

# 2. No more than three warehouses can be operational in any given week.
constraints.append(cp.sum(open_warehouse) <= 3)

# 3. Either the Atlanta or the Los Angeles warehouse must be opened.
constraints.append(open_warehouse[1] + open_warehouse[3] >= 1)

# Each region's demand must be met
for r in range(num_regions):
    constraints.append(cp.sum(ships[:, r]) == demands[r])

# Shipments from a warehouse can only happen if the warehouse is open
for w in range(num_warehouses):
    for r in range(num_regions):
        constraints.append(ships[w, r] <= open_warehouse[w] * max_shipping)

# Objective: Minimize total cost
total_cost = cp.sum([open_warehouse[w] * fixed_costs[w] for w in range(num_warehouses)]) + \
             cp.sum([ships[w, r] * shipping_costs[w][r] for w in range(num_warehouses) for r in range(num_regions)])

# Model
model = cp.Model(constraints, minimize=total_cost)

# Solve the model
if model.solve():
    solution = {
        "total_cost": total_cost.value(),
        "open_warehouse": open_warehouse.value().tolist(),
        "ships": ships.value().tolist()
    }
    print(json.dumps(solution, indent=4))
else:
    print("No solution found")
```

**Comment by Wout4** [comment]
The Value function of the sum operator takes the sum of the values, and here we use np.sum(). That's why we get a numpy object back. I think you can just convert it to an integer before making the json? Just like you convert the numpy lists to python lists. We don't want to do that in general because we might overflow.

**Comment by IgnaceBleukx** [comment]
I did some more digging into this. In Python3, integers are unbounded so actually there is no risk on overflowing when computing the value (at least not for reasonable ranges).
https://docs.python.org/3/library/exceptions.html#OverflowError
https://stackoverflow.com/questions/52151647/integer-overflow-in-python3

```python
import sys
sys.maxsize # 2 ** 63 + 1
>> 9223372036854775807
sys.maxsize * 2
>> 18446744073709551614 # no overflow!
```
There are extreme cases such as the one described here, but also numpy would not solve the issue here.
https://discuss.python.org/t/how-may-we-avoid-overflow-errors/14606

We should make sure all values of all variables are indeed of type `int` as we promise this in our documentation...
I'll open a PR to convert all of these
