### ISSUE TITLE
minizinc solver: how to get all solutions fast

### ISSUE THREAD

**Issue by hakank** [CPMpy/cpmpy#51]
Here is a program which compares three different solvers on a simple model:
```python
from cpmpy import *
from cpmpy.solvers import *
from cpmpy.solvers.utils import get_supported_solvers
import numpy as np
import time

def get_different_solution(m,x):
  """
  get_different_solution(m,x)
  
  Add current solution to the model m for generating other solutions.
  """
  m += [any([t.value() != t for t in x])]

def increasing(args):
  """
  Ensure that the values in args are increasing.
  """
  return [args[i-1] <= args[i] for i in range(1,len(args))]


def test2(solver):
  print("solver:",solver)
  
  n = 3


  x = intvar(0,n, shape=n,name="x")
  z = intvar(0,n*n,name="z")
  print("x:",x)

  model = Model([
    # increasing(x),
    
    # AllDifferent_except_0(x), # same error
    

    # This works but is slow
    AllDifferent(x),
  
    # This works but is extremely slow!
    # z == sum(x),
    z == x.sum(),    
    ])
  
  print("model:", model)
  num_solutions = 0

  if solver == "ortools":
   # solver with ortools
    t1 = time.time()
    ss = CPM_ortools(model)
    while ss.solve():
      num_solutions += 1
      print("x:",x.value(),"z:",z.value(),flush=True)
      get_different_solution(ss,x)    
    print("num_solutions:", num_solutions)
    t2 = time.time()
    print("ortools time:", t2-t1)
    print()
    
  elif solver == "minizinc":
    # Solve with minizinc
    t3 = time.time()
    ss = CPM_minizinc(model)
    # ss = CPM_minizinc(model,"or_tools") # Setting to a specific don't seems to matter. See below
    while ss.solve():
      num_solutions += 1
      print("x:",x.value(),"z:",z.value(),flush=True)
      get_different_solution(ss,x)
      t4 = time.time()
    print("minizinc time:", t4-t3)
    
  else :
    # Default solver
    t3 = time.time()
    while model.solve():
      num_solutions += 1
      print("x:",x.value(),"z:",z.value(),flush=True)
      get_different_solution(model,x)
      t4 = time.time()
    print("minizinc time:", t4-t3)
  
test("ortools")
test("minizinc")
test("default")
```

The time for the MiniZinc approach is significantly slower than the two other approaches:
```
ortools time: 0.05745697021484375
minizinc time: 5.6118950843811035
default time: 0.13840413093566895
```

The file `minizinc.py` mention `all_solutions=True` as a parameter which I assume should be used like this:
```
   # ...
    ss = CPM_minizinc(model)
    while ss.solve(**all_solutions=True)**:
    # ...
```

But then the output is not correct:
```
Warning, no value for  x_0
Warning, no value for  x_1
Warning, no value for  x_2
Warning, no value for  z
x: [None None None] z: None
```

Note that it don't matter which FlatZinc solver that is used. I tested with some different solvers such as gecode, chuffed, or_tools, picat_sat (using `ss = CPM_minizinc(model,"")`) but there wasn't any speedup.

What have I missed?

**Comment by tias** [comment]
About the actual code and experiment:

Interesting, I did not expect the difference to be so big...
I benchmarked the steps inside 'solve', it seems that both:
`mzn_inst = minizinc.Instance(self.mzn_solver, copy_model)`
and `mzn_result = mzn_inst.solve(**kwargs)`
take about 0.1 seconds each; leading to 0.2 seconds per iteration for 24 solutions, which is 4.8 seconds; the runtime of your script on my computer... so, the overhead is in the minizinc-python interface itself (could be its file writing and subprocess starting; perhaps I could use Instance.branch() but that requires branch bookkeeping I think, did not dive deeper).


About your comment of how to get all_solutions=True from the CPM_minizinc interface, well, the solver does compute all solutions (and reports the correct runtime) when you call `ss.solve(all_solutions=True)`, but you have no way to get the solutions at this point... 

Just giving you access to mzn_result is not going to be satisfactory either, because it does not reverse-map to the cpmpy variables, and you only get it after all solutions are found.

minzinc-python does contain a way to async get the solutions, but that requires a different api then `while ss.solve(): do...`.

So... I'm not sure yet how to proceed on native 'all_solutions' for minizinc...

**Comment by tias** [comment]
I tried with creating an Instance once and doing a branch() in solve, but the 'branch' seems to take about the same time as create a new instance, and the solve was a bit slower...

so, yeah, no clear way for a native all_solutions that works identically for ortools and minizinc from the CPMpy APi side..., I'll think about it

**Comment by hakank** [comment]
Thanks for the explanation, Tias.

I didn't realize that cpmpy did a round trip to minizinc-python for each different solution. I've somewhat imagined that it fetched all solutions in one batch and then handed one solution at a time to me...

So for now it's probably best to use MiniZinc for optimization models and for getting first (and second) solutions.

**Comment by tias** [comment]
I was improving the ortools callbacks, from CPMpy, a bit, and ended up adding, for ortools: (commited but not yet released)

```
s = CPM_ortools(model)
s.solveAll() # just returns count
s.solveAll(x) # returns count and prints x.value()
s.solveAll([x,y]) # prints as expected too

# custom print functions
def myprint(variables):
    x, y = variables # we know we will give it 'x,y' as variables
    print(f"x={x.value()}, y={y.value()}")
s.solveAll([x,y], printer=myprint)
```

I think I could add an s.solveAll() with the same signature for minizinc too... will take a bit more time.

What do you think about such an interface for getting all solutions?

**Comment by hakank** [comment]
@tias I really like your suggestion of the `s.solveAll()` family very much. It would certainly help with the (often tedious) work of looping through the solutions and printing the variables. I especially like the version with the `printer` callback since this would help with the (always tedious) work of writing an OR-tools printer callback-

You indicated that you have committed this, but I cannot find it in `master` branch.  Which branch did you commit it to?

That said, it would be even greater to have this feature of a simpler way of printing the output for just the first solution (or in general `n` solutions), i.e. adding a `n_solutions` parameter.  The boring part is not getting _all_ solutions, but getting more than one solution, and especially writing the results for a little more complex output.

And then `solveAll(x)`, `solveAll([x,y])`, and `solveAll({x,y], printer=myprint)` should perhaps be called something else, such as `solvePrint()` (or a better name), and `solveAll()` could be called `solveCountAll()` (or - again - a better name).

**Comment by hakank** [comment]
@tias  I realized that I didn't answer your last question:
__What do you think about such an interface for getting all solutions?__ (for the MiniZinc interface).

Yes, that would be great. Ideally it would be nice if it also supported the number of solutions, but the problem I have with MiniZinc is that generating all solutions is very slow, so the `solveAll()` (and the variants) even without `n_solution` would be very helpful.

I also want to mention that I in fact often want to generate all solutions, however sometimes only the number of solutions so your  different versions of `solveAll()` are great. (The number of solutions I tend to check are: 1 solution for getting just any solution, 2 solutions for checking/proving the uniqueness of the solution, and then all solutions.)

**Comment by tias** [comment]
I reverted it from main and created a new branch, as so many aspects of CPMpy it seems like it can benefit from some more thought and a uniform implementation.

About the name, I think `solveAll` is appropriate for the query, as would `solveCount` be, but 'all solution search' is a more common description hence my preference for solveAll I think...

I see it as a query, which should return the count so that you can easily use it in meta-algorithms. For me, the displaying/printing is just a convenience on top.

That said, I do agree/realize that the 'variables' argument gives the impression that it influences what happens in the function (e.g. a projection) which is not at all the case. Also that it could be made even more convenient, namely to accept either nothing, a (list of) arbitrary CPMpy expressions (including, e.g. an objective function expression) or a python callback function. I refactord in that that way, example uses:

```
x = intvar(0,3, shape=2)
m = Model(x[0] > x[1])
s = CPM_ortools(m)

s.solveAll()
s.solveAll(display=x)
s.solveAll(display=[x,sum(x)])

def newprint():
    print(f"x0:{x[0].value()}")
s.solveAll(display=newprint)

solutions = []
def collect():
    print(x.value())
    solutions.append(x.value())
s.solveAll(display=collect)

print(solutions)
```
the latter is possible because Python actually has very flexible closure mechanisms on its functions...

Another simplification done in the above is that there is just one argument 'display' both for lists/expressions and a callback...


Then, finally, about the solution limit; we also have time_limit, so I guess it makes sense:
```
solveAll(s, display=[x, sum(x)], solution_limit=3)
```

I think this is pretty neat and covers our discussions?

I would then preferably make this an API call of Model() and all solver-specific interfaces (with as fallback the blocking-clause version if the solver has no native support). + docs etc...

**Comment by hakank** [comment]
@tias I agree with you: It's both neat and covers our discussions, and I like it very much!  All your examples above work. Great work!

Some small issues. I'm using this model:
```python
x = intvar(0,3, shape=2)
m = Model(x[0] > x[1])
s = CPM_ortools(m)

```

* `num_solutions = s.solveAll(solution_limit=2)`
   `num_solutions` is 6, not 2 which I have expected. The call might seems to be strange but it can be useful to check if the model have a unique solution.

* `num_solutions = s.solveAll(display=f"x={x.value()} sum(x)={sum(x.value())}")`
    This don't print anything, just returns the number of solutions.  It's not in your list of usage examples and I'm not sure if it should work.

* ` num_solutions = s.solveAll(log_search_progress=True) ` 
    (This might be an old issue.)
    All the outputs are written twice, e.g. 

```
Starting CP-SAT solver.
Starting CP-SAT solver.
Parameters: log_search_progress: true enumerate_all_solutions: true
Parameters: log_search_progress: true enumerate_all_solutions: true


Initial satisfaction model '':
#Variables: 2
  - 2 in [0,3]
#kLinear2: 1
Initial satisfaction model '':
#Variables: 2
  - 2 in [0,3]
#kLinear2: 1

```

**Comment by tias** [comment]
- 6 not 2, that was a bug, the check was in the display part instead of outside
-  doesn't print: it should be either a list or a function, in your case:
```s.solveAll(display=lambda: print(f"x={x.value()} sum(x)={sum(x.value())}"))```

- log double: could you file this as a separate issue, it is probably due to the way I 'fixed' it to display properly in notebooks.

Thx!
Tias

**Comment by hakank** [comment]
@tias  

The "6 for 2" bug is fixed. And I should have realize that it needed a `lambda: print(.)` to work. Great!

I'll file an issue on the double log-

**Comment by tias** [comment]
We've implemented a generic version, with the more efficient solver-specifc one for ortools and MiniZinc (which was subtle to get right).

It is master, we hope to do a new beta release with the unified solver interfaces in as well before the end of the week, let's see : )

So, issue closed and I'm very happy with solveAll() as a new inference method next to solve()

Thanks for the discussions Hakan!
